create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references products(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, product_id)
);

alter table favorites enable row level security;

create policy "Users can view own favorites" on favorites for select using (auth.uid() = user_id);
create policy "Users can insert own favorites" on favorites with check (auth.uid() = user_id);
create policy "Users can delete own favorites" on favorites for delete using (auth.uid() = user_id);
